### ISSUE TITLE
Installation fails for some regions (AU) when trying to download UnicodeData.txt from unicode.org via http (works via ftp).

### ISSUE THREAD

**Issue by klonos** [facelessuser/backrefs#5]
This was initially filed under the wrong issue queue: https://github.com/facelessuser/sublime-backrefs/issues/3

http://www.unicode.org/Public/5.2.0/ucd/UnicodeData.txt times out (tested Telstra cable and Vodafone AU tethered), but ftp://ftp.unicode.org/Public/5.2.0/ucd/UnicodeData.txt works just fine.

Perhaps falling back to ftp if http fails is the solution here.

**Comment by klonos** [comment]
...related articles from around the net:

http://help.appveyor.com/discussions/problems/6012-test-fails-to-connect-to-unicodeorg

https://github.com/keystonejs/keystone/issues/2400

https://github.com/dodo/node-unicodetable/issues/19

https://github.com/dodo/node-unicodetable/issues/16#issuecomment-288306521

>Unicode throttles excess Downloads.

**Comment by facelessuser** [comment]
bah...that's no good.  I wish there was a CDN for this kind of info.  I download it so that I don't explicitly have to update the package for every Python version...and to avoid shipping it with the build to prevent the package getting bigger and bigger for every new Python version it supports.

**Comment by facelessuser** [comment]
I should have a new version out tonight or tomorrow that will timeout and fallback to ftp on error.  It's probably a short term solution, but hopefully it will be good enough for now.

**Comment by facelessuser** [comment]
Ugh.  I seem to be timing out in Travis CI...I guess for now I'll favor ftp over http.  But I may need a better long term solution.

**Comment by facelessuser** [comment]
Ftp failed on the last file.  I guess relying on unicode.org in general is just becoming less of a viable option...I'll take a look at this more tomorrow.

**Comment by klonos** [comment]
Thank you for working on this @facelessuser ...let me know if you need help with testing things.

**Comment by facelessuser** [comment]
I'm going to have to do one of three things:

- ship the release with the Unicode data for all pythons (~5MB for each Python version).  I could zip them though to reduce size and unpack on generation.
- ship the release with only the Python code already generated for every Python version (~1MB for each Python version, though a little bigger for PY27 as I would provide both wide and narrow tables to accommodate both wide and narrow Unicode python builds ).
- Host the unicode data somewhere else and download from there.

I'll have to think about this.  I guess ideally being able to install without more downloads is better especially since I'm not sure where I'd host this Unicode data.  I guess I could just put it up on github and download from there...

Packaging Unicode data, I image I would increase release sizes by ~30MB  Unless I zipped them. Then I could get it down to about ~7MB increase.  Unless I drop something like PY32 support or PY33 support.

Packaging all the generated Python tables will put me at ~8MB.  I could zip all of those and only unpack them on build  I imagine that would be much smaller.  I could just rewrite the auto gen scripts to alternatively unpack the zips if available.

Some ideas to play around with...

**Comment by facelessuser** [comment]
Besides an unrelated document spelling error, looks like including zips of Unicode data passes: https://travis-ci.org/facelessuser/backrefs/builds/261566727.

Will probably throw up some appveyor tests to make sure this is good on windows as well before release, but I imagine it would be.  Maybe later today I'll actually get this out.  I guess in the future, I will prune really old Python builds like 3.2 etc. to reduce release size.  In 2020 I may kill off Python 2.7 support completely as Python2 will be end of life.

**Comment by facelessuser** [comment]
For now, I am just providing zips with the Unicode data for each supported Python version.  Long term this may or may not change, but it should get things reliably working for now.

**Comment by facelessuser** [comment]
1.0.2 is released.  Hopefully that fixes everything for you.  Let me know if doesn't.

**Comment by klonos** [comment]
It installed just fine this time 👍  Thank you!!!

I can now start testing this and I guess you'll see more of me in the issue queue (I'll try not to be much of a pest 😄 ).

Perhaps you might remember that I mentioned in a previous discussion that I am a Windows user that had to switch to Mac for work. So I was looking for a Mac OS equivalent of [dnGrep](http://dngrep.github.io/) and Rummage seems to be a really close match 👍 

Quick question: is the command line the only way to invoke the GUI in the current folder? I am used to that feature on Windows (right-clicking -> selecting dnGrep from the options) and would absolutely love it if rummage would support something similar on Mac.

**Comment by klonos** [comment]
...never mind. I've found [the documentation](http://facelessuser.github.io/Rummage/usage/#macos). I'm having some issues with that, but we are getting off-topic with this. I'll try a bit more and file a separate ticket. Perhaps the documentation needs to be updated ...and I can help with that 😄 

Thank you once again @facelessuser for this amazing project and for all your help with this specific problem 👍

**Comment by facelessuser** [comment]
> I can now start testing this and I guess you'll see more of me in the issue queue (I'll try not to be much of a pest 😄 ).

It's good to get feedback.  Especially on bugs that I am unaware of.

> I'm having some issues with that, but we are getting off-topic with this. I'll try a bit more and file a separate ticket.

Not a problem.  I use Rummage quite frequently on macOS and Windows, so I am sure I get you up and running with the context menu.  Remember though that on macOS, your context entry will be under `Services`.  I'm not sure how to get them at the root level.  Mac is kind of weird about those kind of things.
